### ISSUE TITLE
Rejection thrown if wifi is not configured

### ISSUE THREAD

**Issue by dave92082** [hellogrojo/pi-utils#1]
If the WiFi network is not currently connected to a wireless network and a wpa_supplicant.conf does not exists, wifi.connect fails and will not bring up the interface. This seems to be  because the command that is being passed: 

`sudo /sbin/ifup wlan0`

fails with the result: 

`wpa_supplicant: cannot read contents of /etc/wpa_supplicant/wpa_supplicant.conf`
`run-parts: /etc/network/if-pre-up.d/wpasupplicant exited with return code 1`
`Failed to bring up wlan0.`

Great library! I'll try to do a pull request for this issue.

**Comment by aaronhastings** [comment]
https://github.com/hellogrojo/pi-utils/pull/2
